name: Release

on:
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "28.2"
          elixir-version: "1.19.4"
      - uses: mlugg/setup-zig@v2
        with:
          version: "0.15.2"
      - run: sudo apt-get install -y xz-utils
      - uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: mix-${{ hashFiles('mix.lock') }}
      - run: mix deps.get
      - run: mix test
      - run: MIX_ENV=prod mix release sev
      - uses: softprops/action-gh-release@v2
        with:
          files: burrito_out/*
          generate_release_notes: true
